---
- name: update repositorio
  become: true
  shell: apt-get update -y

- name: install mariadb
  become: true
  apt:
    name:
      - mariadb-server
      - python3-mysqldb
    state: latest

- name: start mariadb
  become: true
  service:
    name: mariadb
    enabled: true
    state: started

- name: mysql_root_password
  become: true
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost

# - name: remove remote root
#   become: true
#   mysql_user:
#     check_implicit_admin: true
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     user: root
#     host: "{{ ansible_fqdn }}"
#     state: absent

- name: Copy my.cnf
  become: yes
  ansible.builtin.copy:
    src: files/my.cnf
    dest: /etc/alternatives/my.cnf
    owner: root
    group: root
    mode: '0777'

- name: Reload systemd httpd, in all cases
  become: true
  ansible.builtin.systemd:
    name: mariadb.service
    state: restarted

- name: Create a new database with name suitecrm
  become: true
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: suitecrm
    state: present

- name: Run several insert queries against db test_db in single transaction
  become: true
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    query: 
    - GRANT ALL ON suitecrm.* to 'root'@'192.168.1.41' IDENTIFIED BY 'teste123';
    - FLUSH PRIVILEGES;
    single_transaction: yes