---
- name: Atualização do repositório ubuntu
  become: true
  shell: apt-get update -y

- name: Instalação do MariaDB
  become: true
  apt:
    name:
      - mariadb-server
      - python3-mysqldb
    state: latest

- name: Inicialização do serviço MariaDB
  become: true
  service:
    name: mariadb
    enabled: true
    state: started

- name: Definição do usuário mysql
  become: true
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_root_user }}"
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost

# - name: remove remote root
#   become: true
#   mysql_user:
#     check_implicit_admin: true
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     user: root
#     host: "{{ ansible_fqdn }}"
#     state: absent

# - name: Cópia de configuração para habilitar 0.0.0.0 e porta 3306
#   become: yes
#   ansible.builtin.copy:
#     src: files/my.cnf
#     dest: /etc/alternatives/my.cnf
#     owner: root
#     group: root
#     mode: '0777'

- name: Permite acesso 0.0.0.0
  become: true 
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "bind-address            = 127.0.0.1"
    line: "bind-address            = 0.0.0.0"
    state: present

- name: Permite porta 3306
  become: true 
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "#port                   = 3306"
    line: "port                   = 3306"
    state: present

- name: Reinicio do serviço MariaDB para aplicação de mudanças
  become: true
  ansible.builtin.systemd:
    name: mariadb.service
    state: restarted

- name: Cria uma nova base com o nome "suitecrm"
  become: true
  community.mysql.mysql_db:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: suitecrm
    state: present

- name: Garante privilégio de conexão para o usuário  "{{ mysql_root_user }}"  vindo do IP {{ suitecrm_ip }}
  become: true 
  community.mysql.mysql_query:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    query: 
    - GRANT ALL ON suitecrm.* to '{{ mysql_root_user }}'@'{{ suitecrm_ip }}' IDENTIFIED BY '{{ mysql_root_password }}';
    - FLUSH PRIVILEGES;
    single_transaction: yes


