---
- name: "Cria o caminho para o serviço"
  become: true
  shell:  mkdir -p /etc/systemd/system/docker.service.d/

- name: Copy override.conf
  become: yes
  copy:
    src: files/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0777'

- name: "Reload no daemon"
  become: true
  shell: systemctl daemon-reload

- name: "Restart no serviço docker"
  become: true
  shell: systemctl restart docker.service
