---
- name: update repositorio
  become: true
  shell: apt-get update -y

- name: install php, modulos, zip & apache
  become: true
  apt:
    name:
      - php7.4
      - zip
      - php7.4-mysql
      - php7.4-xml
      - php7.4-zip
    state: latest

- name: start apache2
  become: true
  service:
    name: apache2
    enabled: true
    state: started

# - name: Download suitecrm.zip
#   become: true
#   get_url:
#     url: https://suitecrm.com{{ suitecrm_url }}
#     dest: /root/suitecrm.zip
#     mode: '0777'

- name: Extract suitecrm.zip into /home/
  become: true
  ansible.builtin.unarchive:
    src: https://suitecrm.com{{ suitecrm_url }}
    dest: /home/
    remote_src: yes

- name: Copy file from /home/{{ suitecrm_version }}/ with owner and permissions to /var/www/html
  become: true
  ansible.builtin.copy:
    src: /home/{{ suitecrm_version }}/
    dest: /var/www/html
    owner: www-data
    group: www-data
    mode: "0775" 
    remote_src: yes
    directory_mode: yes

# - name: Copy config_si
#   become: yes
#   ansible.builtin.copy:
#     src: files/config_si.php
#     dest: /var/www/html
#     owner: root
#     group: root
#     mode: '0775'

- name: Change file ownership, group and permissions /var/www/html/custom/
  become: true
  ansible.builtin.file:
    path: /var/www/html/custom/
    owner: www-data
    group: www-data
    mode: '0766'

- name: Change file opermissions item.path
  become: true
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    mode: '0777'
  loop:
    - { path: /var/www/html/cache/ }  
    - { path: /var/www/html/cache/images } 
    - { path: /var/www/html/cache/layout } 
    - { path: /var/www/html/cache/pdf } 
    - { path: /var/www/html/cache/xml } 
    - { path: /var/www/html/cache/include/javascript }

- name: Remove file (delete file) /var/www/html/index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent