version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    image: suitecrm_mono
    ports:
      - "5000:80"
  db:
    image: mariadb:10.3.31
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=suitecrm
      - MARIADB_ROOT_PASSWORD=root
